title: Hi! I'm Socorro Dominguez
description: > # this means to ignore newlines until "baseurl:"
  Recent UBC Master of Data Science program. I find passion in translating data into business problems' solutions.
permalink: ':title/'
baseurl: #"/sedv8808.github.io" # the subpath of your site, e.g. /blog
url: "http://sedv8808.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Socorro Dominguez Vidana # add your name
author-img: socorro_dominguez.jpg # add your photo
about-author: Always hungry to keep learning, I pursued a Master of Data Science at UBC.  # add description
social-twitter: sedv8808 # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: sedv8808 # add your Github handle
social-linkedin: sedv8808 # add your Linkedin handle
social-email: sedv8808@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
