project:
  type: website
  output-dir: docs

website:
  title: "HT-Data.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: services.qmd
        text: Consulting

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

